//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanSketchers.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrbanSketchers.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Urban Sketches.
        /// </summary>
        internal static string AboutUrbanSketches {
            get {
                return ResourceManager.GetString("AboutUrbanSketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketches flagged as inappropriate must have a comment.  {0}.
        /// </summary>
        internal static string AddCommentMessage {
            get {
                return ResourceManager.GetString("AddCommentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sketch.
        /// </summary>
        internal static string EditSketch {
            get {
                return ResourceManager.GetString("EditSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Comment.
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate Sketch.
        /// </summary>
        internal static string InappropraiteSketch {
            get {
                return ResourceManager.GetString("InappropraiteSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropraite sketches include:
        ///1. Sketches that are not submitted by the original artist.
        ///2. Sketches that are offensive..
        /// </summary>
        internal static string InappropriateSketchDescription {
            get {
                return ResourceManager.GetString("InappropriateSketchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sketches.
        /// </summary>
        internal static string MySketches {
            get {
                return ResourceManager.GetString("MySketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only edit sketches that you submitted..
        /// </summary>
        internal static string OnlyEditOwnSketches {
            get {
                return ResourceManager.GetString("OnlyEditOwnSketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketches.
        /// </summary>
        internal static string Sketches {
            get {
                return ResourceManager.GetString("Sketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sketches by {1}.
        /// </summary>
        internal static string SketchesByFormat {
            get {
                return ResourceManager.GetString("SketchesByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Map.
        /// </summary>
        internal static string SketchMap {
            get {
                return ResourceManager.GetString("SketchMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        internal static string TitleBySketcher {
            get {
                return ResourceManager.GetString("TitleBySketcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to upload a picture to the Urban Sketches service at
        ///http://urbansketchers.azurewebsites.net.
        ///
        ///Please follow these rules when sharing sketches:
        ///1. The sketches should represent actual places that can be mapped on the Earth.
        ///2. You should only upload pictures of sketches that you created.
        ///3. Offensive or pornographic images are not allowed.
        ///4. Place the pictures with an appropriate location, title, and date created.  Description and address are optional.
        ///5. the Urban Sketches App, Site, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UploadMessage {
            get {
                return ResourceManager.GetString("UploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Sketch.
        /// </summary>
        internal static string UploadSketch {
            get {
                return ResourceManager.GetString("UploadSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban Sketchers.
        /// </summary>
        internal static string UrbanSketchers {
            get {
                return ResourceManager.GetString("UrbanSketchers", resourceCulture);
            }
        }
    }
}
